### ISSUE TITLE
name 'client' is not defined

### ISSUE THREAD

**Issue by charleeid** [JetSimon/vidgen#1]
Hi, 

I am getting the error 'name 'client' is not defined' on the line 'voices = client.list_voices()' 

Any suggestions?

Thank you
Charlee

**Comment by JetSimon** [comment]
Please ensure you have the environment variable GOOGLE_JSON_PATH set in your .env file.

If this is not set then the client variable will be null. I'm pushing an error message for that now. So if you pull and run again you can let me know if that occurs.

**Comment by JetSimon** [comment]
I have just made a change so it should work even if GOOGLE_JSON_PATH is undefined. Please let me know if that fixes your issue :)

**Comment by charleeid** [comment]
Yes! That works now thank you. 

Now I just need to figure out what I did wrong with the google_json_path....

Hahaha Thanks though fab!

**Comment by JetSimon** [comment]
Awesome good to hear. Let me know if you run into any more errors. I know there are quite a few edgecases that don't throw warnings currently :)
